name: CA task23 CI/CD

on:
    push:
        branches:
            - main
        paths:
            - '23/**'
    workflow_dispatch:

jobs:
    Build:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v4.2.2
          
          - name: Run build
            run: docker build -t kompromatas/nginx:latest ./23/

          - name: Docker login
            run: echo "${{ secrets.DOCKER_ACCESS_TOKEN}}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

          - name: Push to Docker Hub
            run: docker push kompromatas/nginx:latest
    
    Azure-VM:
        runs-on: ubuntu-latest
        needs: Build
        steps:
            - name: Checkout code
              uses: actions/checkout@v4.2.2

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v2.0.0
              with:
                terraform_version: 1.5.7
            - name: List current directory
              run: ls -R

            - name: Terraform Init
              run: terraform -chdir=23 init

            - name: Terraform Validate
              run: terraform -chdir=23 validate

            - name: Azure Login
              uses: azure/login@v2.3.0
              with:
                creds: ${{ secrets.AZURE_CREDENTIALS }}

            - name: Terraform Plan
              run: terraform -chdir=23 plan -out=tfplan

            - name: Terraform Apply
              run: terraform -chdir=23 apply -auto-approve tfplan
            
            - name: Get VM IP
              id: tfoutput
              run: |
                RAW_OUTPUT=$(terraform -chdir=23 output -raw public_ip)
                IP=$(echo "$RAW_OUTPUT" | grep -Eo '([0-9]{1,3}\.){3}[0-9]{1,3}' | head -n 1)

                if [[ -z "$IP" ]]; then
                  echo "❌ Failed to parse public IP."
                  exit 1
                fi

                echo "✅ Parsed IP: $IP"
                echo "VM_IP=$IP" >> "$GITHUB_ENV"
#              run: echo "VM_IP=$(terraform -chdir=23 output -raw public_ip)" >> $GITHUB_ENV

    Prepair-and-Deploy:
        runs-on: ubuntu-latest
        needs: Azure-VM
        steps:
            - name: checkout code
              uses: actions/checkout@v4.2.2

            - name: Run Ansible playbook
              run: |
                echo "[azure_vm]" > inventory
                echo "$VM_IP"
                echo "$IP" >> inventory
                cat inventory
                ansible-playbook -i inventory 23/playbook.yml --extra-vars "ansible_user=${{ secrets.AZURE_VM_USERNAME }} ansible_password=${{ secrets.AZURE_VM_PASSWORD }}"

    Test:
        runs-on: ubuntu-latest
        needs: Prepair-and-Deploy
        steps:
            - name: Checkout code
              uses: actions/checkout@v4.2.2
            
            - name: Verify deployment
              run: curl -sSf http://${{ env.VM_IP }} | grep "Sveiki atvyke!"