name: CA task23 CI/CD

on:
    push:
        branches:
            - main
        paths:
            - '23/**'
    workflow_dispatch:

jobs:
    Build:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v4.2.2
          
          - name: Run build
            run: docker build -t kompromatas/nginx:latest ./23/

          - name: Docker login
            run: echo "${{ secrets.DOCKER_ACCESS_TOKEN}}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

          - name: Push to Docker Hub
            run: docker push kompromatas/nginx:latest
    
    Azure-VM:
        runs-on: ubuntu-latest
        needs: Build
        steps:
            - name: Checkout code
              uses: actions/checkout@v4.2.2

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v2.0.0
              with:
                terraform_version: 1.5.7
            
            - name: Terraform Init
              run: terraform init

            - name: Terraform Validate
              run: terraform validate

            - name: Azure Login
              uses: azure/login@v2.3.0
              with:
                creds: ${{ secrets.AZURE_CREDENTIALS }}

            - name: Terraform Plan
              run: terraform plan -out=tfplan

            - name: Terraform Apply
              run: terraform apply -auto-approve tfplan
            
            - name: Get VM IP
              id: tfoutput
              run: echo "VM_IP=$(terraform output -raw public_ip)" >> $GITHUB_ENV

    Prepair-and-Deploy:
        runs-on: ubuntu-latest
        needs: Azure-VM
        steps:
            - name: checkout code
              uses: actions/checkout@v4.2.2

            - name: Run Ansible playbook
              run: |
                echo "[azure_vm]" > hosts
                echo "${{ env.VM_IP }}" >> hosts
                ansible-playbook -i hosts playbook.yml --extra-vars "ansible_user=${{ secrets.AZURE_VM_USERNAME }} ansible_password=${{ secrets.AZURE_VM_PASSWORD }}"

    Test:
        runs-on: ubuntu-latest
        needs: Prepair-and-Deploy
        steps:
            - name: Checkout code
              uses: actions/checkout@v4.2.2
            
            - name: Verify deployment
              run: curl -sSf http://${{ env.VM_IP }} | grep "Sveiki atvyke!"