name: 38 task CI/CD
on:
    push:
        branches:
            - main
        paths:
            - '38_python/app.py'
    workflow_dispatch:

jobs:
    build:
        runs-on: self-hosted
        steps:
          - name: Checkout code
            uses: actions/checkout@v4.2.2
          
          - name: Run build
            run: docker build -t kompromatas/app-38:latest ./38/

          - name: Debug secrets (for testing only)
            run: |
              echo "Username: ${{ secrets.DOCKER_USERNAME != '' }}"
              echo "Token is set: ${{ secrets.DOCKER_ACCESS_TOKEN != '' }}"

          - name: Docker login
            run: echo "${{ secrets.DOCKER_ACCESS_TOKEN}}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

          - name: Push to Docker Hub
            run: docker push kompromatas/app-38:latest