name: Deploy code to Azure VM
on:
    push:
        branches:
            - main
        paths:
            - '22/**'
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v4.2.2
          
          - name: Run build
            run: docker build -t kompromatas/nginx:latest ./22/

          - name: Docker login
            run: echo "${{ secrets.DOCKER_ACCESS_TOKEN}}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

          - name: Push to Docker Hub
            run: docker push kompromatas/nginx:latest
          
    deploy:
      runs-on: ubuntu-latest
      needs: build
      steps:
        - name: Checkout code
          uses: actions/checkout@v4.2.2

        - name: Deploy to Azure VM
          uses: appleboy/ssh-action@v1.0.0
          with:
            host: ${{ secrets.AZURE_VM_IP }}
            username: ${{ secrets.AZURE_VM_USERNAME }}
            password: ${{ secrets.AZURE_VM_PASSWORD }}
            script: |
              sudo docker pull kompromatas/nginx:latest
              sudo docker stop nginx || true
              sudo docker rm nginx || true
              sudo docker run -d -p 80:80 --name ca-devops kompromatas/nginx:latest
              sudo docker ps

    test:
        runs-on: ubuntu-latest
        needs: deploy
        steps:
            - name: Checkout code
              uses: actions/checkout@v4.2.2
            
            - name: Verify deployment
              run: curl -sSf http://${{ secrets.AZURE_VM_IP }} | grep "Sveiki atvyke!"