name: 21-22 task CI/CD
on:
    push:
        branches:
            - main
        paths:
            - '21/**'
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v4.2.2
          
          - name: Run build
            run: docker build -t kompromatas/ca-devops:latest ./21/

          - name: Debug secrets (for testing only)
            run: |
              echo "Username: ${{ secrets.DOCKER_USERNAME != '' }}"
              echo "Token is set: ${{ secrets.DOCKER_ACCESS_TOKEN != '' }}"

          - name: Docker login
            run: echo "${{ secrets.DOCKER_ACCESS_TOKEN}}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

          - name: Push to Docker Hub
            run: docker push kompromatas/ca-devops:latest
          
    test:
      runs-on: ubuntu-latest
      needs: build
      steps:
        - name: Checkout code
          uses: actions/checkout@v4.2.2

        - name: Run tests
          run: docker run --rm kompromatas/ca-devops:latest /app/test.sh
          
        - name: Upload test results
          uses: actions/upload-artifact@v2
          with:
            name: test-results    


